### PR TITLE
1.0.6

### PR DESCRIPTION
**Pull request by RealyUniqueName**
* updated libs/pako.min.js to pako 1.0.6
* moved package `js.pako` to `pako` to follow native naming
* updated to pako 1.0.6

### CODE REVIEW

**Comment by hamaluik** [comment]
Looks, good, thanks! I will publish the updates on haxelib shortly

**Comment by RealyUniqueName** [comment]
Sorry to bother you, but can you please do it today? Or give me permission so i can publish it myself.

**Comment by hamaluik** [comment]
It's already been published: http://lib.haxe.org/p/pako/1.0.6/

**Comment by RealyUniqueName** [comment]
Thanks!

**Pull request merged**
